### ISSUE TITLE
Lynn mentioned artifact behavior from last names

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#229]
sometimes when she enters a new client, the lastname/family association winds up being from a previous family selection (i.e. 
1. working with the hathaway family
2. selects Berkshire from the family drop down list
3. and adds new client warren
4. warren is associated with Hathaway instead of berkshire

i haven't been able to reproduce this

**Comment by okkam1** [comment]
notes from meeting: will leave open until discussing with Lynne.  Likely this issue will be closed.  if it happens again and is reproducible, we can re-open the ticket.  If this issue is not reproducible, but is causing a lot of pain for the end user, we can setup some time to examine how they are using the app to see if there is potentially a way to reproduce.

**Comment by liamehinc** [comment]
Lynne has not seen this in some time. Closing
